apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-gateway
  template:
    metadata:
      labels:
        app: app-gateway
        version: latest
    spec:
      containers:
      - name: app-gateway
        image: manscalh/app-gateway:latest
        imagePullPolicy: Always
        resources:
        ports:
        - containerPort: 3000