apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 1Deployment.yaml
- 2Deployment-beta.yaml
- 3Service.yaml
- 4VirtualService.yaml
- 5DestinationRule.yaml
- 6IngressGateway.yaml

images:
- name: app-gateway
  newName: manscalh/app-gateway
  newTag: 698f7ed891c71f2c37c0c0945901fb5697f16864
