apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- Deployment.yaml
- Deployment-beta.yaml
- Service.yaml
- VirtualService.yaml
- DestinationRule.yaml
- IngressGateway.yaml

images:
- name: app-gateway
  newName: manscalh/app-gateway
  newTag: 90aa1236f38021b3cefcc80bf246877b2c167c0b
