apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- Deployment.yaml
- Deployment-beta.yaml
- Service.yaml
- VirtualService.yaml
- DestinationRule.yaml
- IngressGateway.yaml

images:
- name: app-gateway
  newName: manscalh/app-gateway
  newTag: 6ec2f1af1f22d658d795a64b63b4904c16d4e503
