apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- Deployment.yaml
- Service.yaml

images:
- name: app-gateway
  newName: manscalh/app-gateway
  newTag: 22ac79e0dcd812514c4099505a7fe2e81a611fa0
