apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- Deployment.yaml
- Deployment-beta.yaml
- Service.yaml
- DestinationRule.yaml
- IngressGateway.yaml

images:
- name: app-gateway
  newName: manscalh/app-gateway
  newTag: f36142390556f14e78fa7fa748792030168ebf11
