apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- Deployment.yaml
- Deployment-beta.yaml
- Service.yaml
- DestinationRule.yaml
- IngressGateway.yaml

images:
- name: app-gateway
  newName: manscalh/app-gateway
  newTag: 9d485a161514b945229afe6722d49ee0e69c1670
