apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- Deployment.yaml
- Deployment-beta.yaml
- Service.yaml

images:
- name: app-gateway
  newName: manscalh/app-gateway
  newTag: 46abf328a6e75de3d9fc8806170b8f541105f1de
